case $- in
  *i*) ;;
  *) return;;
esac

shopt -s -o notify
shopt -s histappend
shopt -s cdspell
shopt -s checkhash
shopt -s checkwinsize
shopt -s cmdhist
shopt -s nocaseglob


if [ $(uname) = "Darwin" ]
then
    export NPM_PACKAGES=$HOME/.npm-packages
    export NODE_PATH=$NPM_PACKAGES/lib/node_modules:$NODE_PATH
    if [ -f $(brew --prefix)/etc/bash_completion ]; then
        source $(brew --prefix)/etc/bash_completion
    fi
    export WORKON_HOME=$HOME/Projects
    test -d $HOME/Projects || mkdir -p $WORKON_HOME
    export PYTHON_HOME_MAC=$HOME/Library/Python/2.7
    export GOROOT=/usr/local/go
    export GOPATH=$HOME/Code
	  export JAVA_HOME=$(/usr/libexec/java_home)
    alias vim=/usr/local/bin/vim
    alias vi=/usr/local/bin/vi
    echo -n "Testing UTF-8: "
    LANG=sv_SE.UTF-8 echo -e "\u2664"
    /bin/cat $HOME/.TIPS >&2
fi


if [ $(uname) = "Linux" ]
then
  export NPM_PACKAGES=$HOME/.npm-packages
  export NODE_PATH=$NPM_PACKAGES/lib/node_modules:$NODE_PATH
	export JAVA_HOME=$HOME/jdk
	export GROOVY_HOME=$HOME/groovy
	export GOROOT=$HOME/go
	export GRADLEHOME=$HOME/gradle
	export GOPATH=$HOME/Code

	alias mysearch="sudo apt-cache search"
	alias myinstall="sudo apt-get install -y"
	alias myupdate="sudo apt-get update"
  alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'
fi


function check_ca_hash() {
	local OPENSSL=$(which openssl)
	local FILE=$1
	$OPENSSL x509 -noout -hash -in $FILE
}

export HISTSIZE=9999
export HISTFILESIZE=9999
export RSYNC_RSH="ssh"
export HISTTIMEFORMAT="%F"
export HISTCONTROL=ignoreboth:erasedups
export GIT_COMMITTER_EMAIL=bundgaard@users.noreply.github.com
export GIT_AUTHOR_EMAIL=bundgaard@users.noreply.github.com
export LESS='-FRsX'
export EDITOR='vi'
export MANPAGER='less'
export PAGER='less'
export ANT_HOME=$HOME/ant
export MAVEN_HOME=$HOME/maven
export LOCAL_HOME=/usr/local
unset MANPATH
export MANPATH=$HOME/man:$HOME/perl5/man:$(manpath)
unset PATH
export PATH=$LOCAL_HOME/bin:$PYTHON_HOME_MAC/bin:$NPM_PACKAGES/bin:$GOROOT/bin:$JAVA_HOME/bin:$ANT_HOME/bin:$MAVEN_HOME/bin:$GRADLEHOME/bin:$GROOVY_HOME/bin:$HOME/bin:$HOME/perl5/bin:/sbin:/bin:/usr/bin:/usr/sbin:/usr/local/bin:/usr/local/sbin


PS1="[\w\\$] "
if [ `uname` = "Darwin" ]; then
    source $HOME/perl5/perlbrew/etc/bashrc
    source /Users/dbundgaard/Library/Python/2.7/bin/virtualenvwrapper.sh
fi

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

test -d $HOME/perl5 && eval "$(perl -I$HOME/perl5/lib/perl5 -Mlocal::lib)"
